name: Build and Upload Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Python version
        uses: actions/setup-python@v3
        with:
          python-version: '3.12.2'

      - name: Install dependencies
        run: python -m pip install pyinstaller

      - name: Build the executable
        run: pyinstaller --onefile --add-data="protontricks/:protontricks/" --add-data="Injector.exe:." pg3d-injector.py

      - name: Upload release artifact
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: dist/*  # Change the pattern if the output filename is different

  publish:
    runs-on: ubuntu-latest
    needs: build  # This job depends on the build job

    steps:
              - name: Create Release
                uses: ncipollo/release-action@v1.14.0
            
            
