name: Build and Release Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.2'  # Replace 'x' with your desired Python version

    - name: Install dependencies
      run: |
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile --add-data="protontricks/:protontricks/" --add-data="Injector.exe:." pg3d-injector.py

    - name: Move executable to dist folder
      run: |
        mkdir -p dist
        mv pg3d-injector/dist/pg3d-injector dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: pg3d-injector
        path: dist/pg3d-injector

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ steps.upload.outputs.artifact }}
        tag: ${{ github.ref }}
        name: Release ${{ github.ref }}
        commit: ${{ github.sha }}
        token: ${{ secrets.GITHUB_TOKEN }}
