name: Build and Release Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Replace 'x' with your desired Python version

    - name: Install dependencies
      run: |
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile --add-data="protontricks/:protontricks/" --add-data="Injector.exe:." main.py

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/*"  # Adjust the path to match your generated executable file
        tag: ${{ github.ref }}
        name: Release ${{ github.ref }}
        commit: ${{ github.sha }}
        token: ${{ secrets.GITHUB_TOKEN }}
